"""Tests for the generated canonical agent asset inventory."""

from __future__ import annotations

import importlib.util
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_PATH = REPO_ROOT / "scripts" / "generate_agent_asset_inventory.py"

spec = importlib.util.spec_from_file_location("generate_agent_asset_inventory", SCRIPT_PATH)
assert spec is not None and spec.loader is not None
generate_agent_asset_inventory = importlib.util.module_from_spec(spec)
spec.loader.exec_module(generate_agent_asset_inventory)


def test_render_inventory_lists_commands_skills_and_agents() -> None:
    rendered = generate_agent_asset_inventory.render_inventory(REPO_ROOT)

    assert "<!-- Generated by scripts/generate_agent_asset_inventory.py; do not edit by hand. -->" in rendered
    assert "| `/spec` | `.claude/commands/spec.md` |" in rendered
    assert "| `security-review` | `.claude/skills/security-review/SKILL.md` |" in rendered
    assert "| `pr-ready-hygiene` | `.claude/agents/pr-ready-hygiene.md` |" in rendered


def test_generated_inventory_is_current() -> None:
    expected = generate_agent_asset_inventory.render_inventory(REPO_ROOT)
    actual = (REPO_ROOT / "docs" / "agent-asset-inventory.md").read_text(encoding="utf-8")

    assert actual == expected


def test_main_accepts_output_outside_repo(tmp_path: Path, capsys) -> None:
    output = tmp_path / "inventory.md"

    result = generate_agent_asset_inventory.main(["--output", output.as_posix()])

    assert result == 0
    assert output.read_text(encoding="utf-8") == generate_agent_asset_inventory.render_inventory(REPO_ROOT)
    assert f"wrote {output.as_posix()}" in capsys.readouterr().out
